# Generated by Django 5.1.3 on 2025-01-07 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Education', 'verbose_name_plural': 'Educations'},
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='skill_name',
            new_name='skill',
        ),
    ]
