# Generated by Django 5.1.3 on 2025-01-07 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0002_alter_education_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalcourse',
            name='completion_date',
        ),
    ]
